### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by aa-dank** [jorisschellekens/borb#124]
**Describe the bug**
I followed your blog post on using borb and tesseract to OCR a pdf, but it is throwing an exception:
```
Traceback (most recent call last):
  File "C:/Users/adankert/Google Drive/GitHub/file_server_management/ocr/ocr_pdf.py", line 22, in build_ocr_pdf_copy
    doc = PDF.loads(pdf_file_handle, [l])
  File "C:\Users\adankert\.virtualenvs\file_server_management-Bevy2CbZ\lib\site-packages\borb\pdf\pdf.py", line 54, in loads
    return ReadAnyObjectTransformer().transform(
  File "C:\Users\adankert\.virtualenvs\file_server_management-Bevy2CbZ\lib\site-packages\borb\io\read\any_object_transformer.py", line 100, in transform
    return super().transform(
  File "C:\Users\adankert\.virtualenvs\file_server_management-Bevy2CbZ\lib\site-packages\borb\io\read\transformer.py", line 123, in transform
    out = h.transform(
  File "C:\Users\adankert\.virtualenvs\file_server_management-Bevy2CbZ\lib\site-packages\borb\io\read\reference\xref_transformer.py", line 76, in transform
    l._event_occurred(BeginDocumentEvent())  # type: ignore [attr-defined]
  File "C:\Users\adankert\.virtualenvs\file_server_management-Bevy2CbZ\lib\site-packages\borb\toolkit\ocr\ocr_as_optional_content_group.py", line 141, in _event_occurred
    if isinstance(event, EndDocumentEvent):
NameError: name 'EndDocumentEvent' is not defined
```
Seems like EndDocumentEvent needs to be instantiated even if the import conditional does not execute. Something like:
```python
# FIX: circular imports (2/2)
from typing import TYPE_CHECKING

EndDocumentEvent = type(None)
if TYPE_CHECKING:
    from borb.io.read.reference.xref_transformer import EndDocumentEvent
```

**To Reproduce**
Script I built from your ocr blog post:

```python
import typing
from pathlib import Path

from borb.toolkit.ocr.ocr_as_optional_content_group import OCRAsOptionalContentGroup
from borb.pdf import Document
from borb.pdf.pdf import PDF


class OCRMachine:
    def __init__(self, tesseract_data_path):
        self.tesseract_data_dir = Path(tesseract_data_path)

    def build_ocr_pdf_copy(self, input_pdf_path, copy_destination_path):

        # Set up everything for OCR
        assert self.tesseract_data_dir.exists()
        l: OCRAsOptionalContentGroup = OCRAsOptionalContentGroup(self.tesseract_data_dir)

        # Read Document
        doc: typing.Optional[Document] = None
        with open(input_pdf_path, "rb") as pdf_file_handle:
            doc = PDF.loads(pdf_file_handle, [l])

        assert doc is not None

        # Store Document
        with open(copy_destination_path, "wb") as pdf_file_handle:
            PDF.dumps(pdf_file_handle, doc)

scanned_pdf_example = r"C:\Users\adankert\Downloads\tess_example.pdf"
example_output_path = r"C:\Users\adankert\Downloads\ocr_example.pdf"
ocr_machine = OCRMachine(tesseract_data_path=r"C:\Program Files\Tesseract-OCR\tessdata")
ocr_machine.build_ocr_pdf_copy(input_pdf_path=scanned_pdf_example,
                               copy_destination_path=example_output_path)
```

**Expected behaviour**
I did not expect it to throw an exception

**Desktop (please complete the following information):**
 - OS: Windows 10
 - borb version 2.0.30
- input PDF (not applicable)
- Python 3.9.11

**Comment by jorisschellekens** [comment]
This minor bug was fixed in the latest release.
I am now re-running all tests as a final check for thus release. 

You may expect the release to be up before midnight.

Kind regards,
Joris Schellekens
