### ISSUE TITLE
Search and Replace of Text not working 

### ISSUE THREAD

**Issue by suramyatomar** [jorisschellekens/borb#149]
I am trying to use Borb to search and replace specif text in PDF's so that I can automate the process.  However, when I try to replace the text using the example from your site (https://github.com/jorisschellekens/borb-examples#77-replacing-text-in-an-existing-pdf) the script fails with the following error:

-----
/usr/bin/python3 /home/suramya/Programs/PDFSearchReplace/BorbReplace.py

Traceback (most recent call last):
  File "/home/suramya/Programs/PDFSearchReplace/BorbReplace.py", line 26, in <module>
    main()
  File "/home/suramya/Programs/PDFSearchReplace/BorbReplace.py", line 18, in main
    doc = SimpleFindReplace.sub("Manual", "", doc)
  File "/usr/local/lib/python3.10/dist-packages/borb/toolkit/text/simple_find_replace.py", line 80, in sub
    page.apply_redact_annotations()
  File "/usr/local/lib/python3.10/dist-packages/borb/pdf/page/page.py", line 271, in apply_redact_annotations
    .read(io.BytesIO(self["Contents"]["DecodedBytes"]), [])
  File "/usr/local/lib/python3.10/dist-packages/borb/pdf/canvas/canvas_stream_processor.py", line 290, in read
    raise e
  File "/usr/local/lib/python3.10/dist-packages/borb/pdf/canvas/canvas_stream_processor.py", line 284, in read
    operator.invoke(self, operands, event_listeners)
  File "/usr/local/lib/python3.10/dist-packages/borb/pdf/canvas/redacted_canvas_stream_processor.py", line 271, in invoke
    self._write_chunk_of_text(
  File "/usr/local/lib/python3.10/dist-packages/borb/pdf/canvas/redacted_canvas_stream_processor.py", line 203, in _write_chunk_of_text
    )._write_text_bytes()
  File "/usr/local/lib/python3.10/dist-packages/borb/pdf/canvas/layout/text/chunk_of_text.py", line 145, in _write_text_bytes
    return self._write_text_bytes_in_hex()
  File "/usr/local/lib/python3.10/dist-packages/borb/pdf/canvas/layout/text/chunk_of_text.py", line 160, in _write_text_bytes_in_hex
    assert cid is not None, "Font %s can not represent '%s'" % (
AssertionError: Font Arial,Bold can not represent 'E'

Process finished with exit code 1

--------

I tried debugging but can't figure out what the issue is and searching on the web didn't give me any relevant answers. I get the same error on the PDF's I have tested this on. This is using Python3 on Debian 11, the PDF version is 1.5 using the latest version of borb (2.1.7 )

Any idea what the problem could be and how to fix it? 

Thanks in advance for the help.

- Suramya

**Comment by jorisschellekens** [comment]
`borb` is already telling you exactly what the error is.

Not every font can represent every possible character in every language.

Since you did not give me a code-snippet I am going to assume you are trying to insert a piece of text that contains a character that Arial can not represent.

Maybe some weird kind of "E" (since uppercase E should not be a problem).

**Comment by suramyatomar** [comment]
The code is as follows. I am trying to replace the word 'Manual' with 123 :

```
from borb.pdf import Document
from borb.pdf import PDF
from borb.toolkit import SimpleFindReplace

import typing

def main():

    # attempt to read a PDF
    doc: typing.Optional[Document] = None
    with open("MAA.pdf", "rb") as pdf_file_handle:
        doc = PDF.loads(pdf_file_handle)

    # check whether we actually read a PDF
    assert doc is not None

    # find/replace
    doc = SimpleFindReplace.sub("Manual", "123", doc)

    # store
    with open("MAA_out.pdf", "wb") as pdf_file_handle:
        PDF.dumps(pdf_file_handle, doc)


if __name__ == "__main__":
    main()
```

**Comment by jorisschellekens** [comment]
Please attach the input document as well. Otherwise I can't reproduce the issue.

**Comment by suramyatomar** [comment]
Ok, this is really strange. I was masking the data in the PDF file to share it with you and the script suddenly started working. There was an extra space after the word PRIVATE in the file and when I removed it things started working (even on the unmasked file). 

So the issue was in the file itself. You can go ahead and close. I will try to figure out how to fix the source file programmatically.
