### ISSUE TITLE
`OSError: [Errno 24] Too many open files` during import

### ISSUE THREAD

**Issue by sweh** [jorisschellekens/borb#154]
I'm getting a `OSError: [Errno 24] Too many open files: '/Users/sweh/Downloads/test/lib/python3.8/site-packages/borb/pdf/canvas/layout/emoji/resources/eight_pointed_blue_star.png'` when importing `Document`:

```
$ python3.8 -m venv test
$ cd test
$ bin/pip install borb
$ bin/python
Python 3.8.13 (default, Mar 20 2022, 04:55:09)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from borb.pdf import Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sweh/Downloads/test/lib/python3.8/site-packages/borb/pdf/__init__.py", line 107, in <module>
  File "/Users/sweh/Downloads/test/lib/python3.8/site-packages/borb/pdf/canvas/layout/text/heterogeneous_paragraph.py", line 15, in <module>
  File "/Users/sweh/Downloads/test/lib/python3.8/site-packages/borb/pdf/canvas/layout/emoji/emoji.py", line 98, in <module>
  File "/Users/sweh/Downloads/test/lib/python3.8/site-packages/borb/pdf/canvas/layout/emoji/emoji.py", line 357, in Emojis
  File "/Users/sweh/Downloads/test/lib/python3.8/site-packages/borb/pdf/canvas/layout/emoji/emoji.py", line 38, in __init__
  File "/Users/sweh/Downloads/test/lib/python3.8/site-packages/borb/pdf/canvas/layout/image/image.py", line 64, in __init__
  File "/Users/sweh/Downloads/test/lib/python3.8/site-packages/PIL/Image.py", line 3227, in open
OSError: [Errno 24] Too many open files: '/Users/sweh/Downloads/test/lib/python3.8/site-packages/borb/pdf/canvas/layout/emoji/resources/eight_pointed_blue_star.png'
```

 - OS: MacOS Ventura 13.2.1 (22D68) on Apple Silicone M1
 - borb version: borb-2.1.9-py3-none-any.whl

**Comment by sweh** [comment]
This is failing for versions >= `2.1.3` for me, so the last working version is `2.1.1` (as there is no `2.1.2` on pypi).

**Comment by jorisschellekens** [comment]
The classes `Emoji` and `Emojis` in `borb` allow you to easily insert emojis into a PDF, even if your `Font` does not support emoji.
However, these classes essentially load 600 or something images.
I think that's what's causing your issue.

**Comment by jorisschellekens** [comment]
I'm trying out something.
I've changed the base class `Image` so it no longer automatically loads an image, but only does so when it needs it.

I'm going to add some print statements to see whether that causes less load operations when importing `Document`

**Comment by jorisschellekens** [comment]
The bug appears to be solved on my system.
I've made a new build for you to try out.
Sadly, GitHub does not allow me to upload `whl` files.

Hence this link: https://we.tl/t-VmVmtzMEU8

This fix will be in the next release, which you may expect coming weekend.

Kind regards,
Joris Schellekens
