### ISSUE TITLE
BUG: `cryptography` and `lxml` dependencies not declared in setup.py

### ISSUE THREAD

**Issue by mportesdev** [jorisschellekens/borb#161]
**Describe the bug**
Runtime dependencies `cryptography` and `lxml` are not declared in setup.py and requirements.txt, leading to `ModuleNotFoundError`.

**To Reproduce**
Steps to reproduce the behaviour:
- create a fresh venv, activate, run `pip install borb`
- in python repl, run `from borb.pdf import PDF`

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michal/venv/lib/python3.11/site-packages/borb/pdf/__init__.py", line 118, in <module>
    from .pdf import PDF
  File "/home/michal/venv/lib/python3.11/site-packages/borb/pdf/pdf.py", line 23, in <module>
    from borb.license.usage_statistics import UsageStatistics
  File "/home/michal/venv/lib/python3.11/site-packages/borb/license/usage_statistics.py", line 17, in <module>
    from borb.license.license import License
  File "/home/michal/venv/lib/python3.11/site-packages/borb/license/license.py", line 25, in <module>
    from cryptography.hazmat.primitives import serialization, hashes
ModuleNotFoundError: No module named 'cryptography'
```

- quit python repl, run `pip install cryptography`
- again in python repl, run `from borb.toolkit import ImageExtraction`

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michal/venv/lib/python3.11/site-packages/borb/toolkit/__init__.py", line 49, in <module>
    from .export.html_to_pdf.html_to_pdf import HTMLToPDF
  File "/home/michal/venv/lib/python3.11/site-packages/borb/toolkit/export/html_to_pdf/html_to_pdf.py", line 12, in <module>
    from lxml.etree import HTMLParser, _Comment  # type: ignore [import]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'lxml'
```

**Desktop:**
 - OS: Ubuntu 22.04
 - borb version 2.1.11
 - Python version 3.11.3

**Comment by jorisschellekens** [comment]
Fixed, version `2.1.12` contains the dependencies needed by `borb`.
Thank you very much for bringing this to my attention!
