### ISSUE TITLE
BUG Simple Find Replace doesn't work

### ISSUE THREAD

**Issue by pig123123** [jorisschellekens/borb#167]
**Describe the bug**
Simple Find Replace exit with Assertion Error because of font

**To Reproduce**
This is the code:

`
from borb.pdf import Document
from borb.pdf import PDF
from borb.toolkit import SimpleFindReplace

import typing

def main():

    #尝试读取PDF
    doc: typing.Optional[Document] = None
    with open("Cover.pdf", "rb") as pdf_file_handle:
        doc = PDF.loads(pdf_file_handle)

    assert doc is not None

    #替换
    doc = SimpleFindReplace.sub(pattern="Cambridge", repl="Math",doc= doc)

    #储存替换文本后的文件
    with open("output_001.pdf","wb") as pdf_file_handle:
        PDF.dumps(pdf_file_handle, doc)

if __name__ == "__main__":
    main()

print("finish_borb")
`

Then the error:

`Traceback (most recent call last):
  File "/Users/rzhu/Desktop/python_learning/pdf_watermark_remove/SimpleFindReplaceWithborb.py", line 25, in <module>
    main()
  File "/Users/rzhu/Desktop/python_learning/pdf_watermark_remove/SimpleFindReplaceWithborb.py", line 18, in main
    doc = SimpleFindReplace.sub(pattern="Cambridge", repl="Math",doc= doc)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/toolkit/text/simple_find_replace.py", line 77, in sub
    page.apply_redact_annotations()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/page/page.py", line 151, in apply_redact_annotations
    RedactedCanvasStreamProcessor(self, Canvas(), rectangles_to_redact)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/canvas_stream_processor.py", line 300, in read
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/canvas_stream_processor.py", line 294, in read
    operator.invoke(self, operands, event_listeners)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/redacted_canvas_stream_processor.py", line 302, in invoke
    self._write_chunk_of_text(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/redacted_canvas_stream_processor.py", line 228, in _write_chunk_of_text
    canvas_stream_processor._redacted_content += ChunkOfText(  # type: ignore[attr-defined]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/layout/text/chunk_of_text.py", line 200, in _write_text_bytes
    return self._write_text_bytes_in_hex()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/layout/text/chunk_of_text.py", line 242, in _write_text_bytes_in_hex
    assert cid is not None, "Font %s can not represent '%s'" % (
AssertionError: Font TRYRVL+HelveticaNeueLTStd-Bd can not represent 'P'`

But in `doc = SimpleFindReplace.sub(pattern="Cambridge", repl="Math",doc= doc)` The word 'Cambridge' and 'Math' don't have the letter 'P'

**Desktop (please complete the following information):**
 - OS: mac big sur
 - borb version 2.1.12
- input PDF (if applicable)
[Cover.pdf](https://github.com/jorisschellekens/borb/files/11582311/Cover.pdf)

**Additional context**
#149 
It seems that I have met the problem which is similar to this issue.

**Comment by jorisschellekens** [comment]
That seems to have no ill side-effects. This fix will be in the next release.
Thank you for taking the time to log a bug.

Kind regards,
Joris Schellekens
