### ISSUE TITLE
Existing PDF seems to have no Resources data

### ISSUE THREAD

**Issue by BenoBenq** [jorisschellekens/borb#189]
In a PDF file somebody else had produced i want to find an expression using the SimpleTextExtraction, but i get "KeyError: 'Resources'" when executing the script. Can it be that the PDF file has no resources attached? Is this a bug or expected behavior?

**To Reproduce**

Use [this](https://github.com/jorisschellekens/borb/files/13777989/Meldeergebnis-NRW-KuBa-2023.pdf) pdf file and store it in the same folder as the script file. Then just run the script

```python
import typing

from borb.pdf import Document
from borb.pdf import PDF
from borb.toolkit import SimpleTextExtraction


def main():

    # read the Document
    doc: typing.Optional[Document] = None
    l: SimpleTextExtraction = SimpleTextExtraction()
    with open("./Meldeergebnis-NRW-KuBa-2023.pdf", "rb") as in_file_handle:
        doc = PDF.loads(in_file_handle, [l])

    # check whether we have read a Document
    assert doc is not None

    # print the text on the first Page
    print(l.get_text()[0])


if __name__ == "__main__":
    main()
```

**Expected behaviour**
It should just read the pdf file and print the content of the first page.

**Result**
But i get this error instead:
```
Traceback (most recent call last):
  File "foo/bar/borbtest.py", line 34, in <module>
    main()
  File "foo/bar/borbtest.py", line 22, in main
    doc = PDF.loads(in_file_handle, [l])
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/pdf/pdf.py", line 83, in loads
    document: Document = ReadAnyObjectTransformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/reference/xref_transformer.py", line 295, in transform
    trailer = self.get_root_transformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/object/dictionary_transformer.py", line 62, in transform
    v = self.get_root_transformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/reference/reference_transformer.py", line 160, in transform
    transformed_referenced_object = self.get_root_transformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/page/root_dictionary_transformer.py", line 100, in transform
    transformed_root_dictionary = t.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/object/dictionary_transformer.py", line 62, in transform
    v = self.get_root_transformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/reference/reference_transformer.py", line 160, in transform
    transformed_referenced_object = self.get_root_transformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/object/dictionary_transformer.py", line 62, in transform
    v = self.get_root_transformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/object/array_transformer.py", line 62, in transform
    object_to_transform[i] = self.get_root_transformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/reference/reference_transformer.py", line 160, in transform
    transformed_referenced_object = self.get_root_transformer().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/any_object_transformer.py", line 113, in transform
    return super().transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/transformer.py", line 149, in transform
    out = h.transform(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/io/read/page/page_dictionary_transformer.py", line 122, in transform
    CanvasStreamProcessor(page_out, canvas, []).read(
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/pdf/canvas/canvas_stream_processor.py", line 293, in read
    raise e
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/pdf/canvas/canvas_stream_processor.py", line 287, in read
    operator.invoke(self, operands, event_listeners)
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/pdf/canvas/operator/xobject/do.py", line 55, in invoke
    xobject = canvas_stream_processor.get_resource("XObject", str(operands[0]))
  File "/home/foo_bar.local/lib/python3.10/site-packages/borb/pdf/canvas/canvas_stream_processor.py", line 208, in get_resource
    resource_type_name in self._page["Resources"]
KeyError: 'Resources'`

```

**Desktop:**
 - OS: Ubuntu 22.04.3 LTS
 - borb version 2.1.20
 - python 3.10.12

**Comment by jorisschellekens** [comment]
Your PDF is corrupt.

There is a wonderful online tool called Vera PDF checker, which offers a convenient "drop the file here to check it" functionality.

This is what comes out of that:

![image](https://github.com/jorisschellekens/borb/assets/18642798/627ae33e-a8b6-42dd-9bb0-55709e0ada86)

Some of these errors might be harmless. But I'm guessing the broken fonts might be the problem here.

Kind regards,
Joris Schellekens

**Comment by BenoBenq** [comment]
Thank you very much! I already suspected that this might be the case. 

Is there anyway that i can still open the pdf using your library while using the EventListener option? Maybe a small code change that still enables me to find occurrences and their boundary box inside the pdf, basically ignoring the fonts?

Or do you maybe have any tips on how i can make it non-corrupted? I tried opening and saving it again with borb, but to no avail.

**Comment by jorisschellekens** [comment]
If the font information isn't present, then it would be impossible to extract text accurately. 

A PDF doesn't store "text". It stores rendering instructions. 

So instead of something like "Hello World", you might find the following content stream in a page (I have added explanation between brackets):

- q (store graphics state)
- /F1 12 Tf (set the font to F1, size 12)
- BT (begin text)
- 70 640 m (move to position 70, 640)
- (Hello) Tj (draw the text "Hello")
- 120 640 m (move to position 120, 640)
- (World) Tj (draw the text "World")
- ET (end text)
- Q (restore the graphics state)

Text does not need to be rendered in "logical reading order". You might draw 'World" before drawing "Hello". You could even draw all the odd letters "_e_l_ _o_l_" and then the even ones.

That would be perfectly legal according to the spec.

So you really need to know where each letter is drawn, and how wide it is. Then you can sort all the letters by x coordinate to figure out which letter to draw first.

What you could do (but this is a horrible idea) is to open the PDF using borb, and attempt to restore it (by inserting the missing font resource dictionaries).

But keep in mind you would have no guarantee that the font you're using is actually a good substitute for the missing font.

Kind regards,
Joris Schellekens
