### ISSUE TITLE
Layout_rect calculation changed between 2.0.21 and 2.0.24 and leads to infinite recursion in multi_column_layout.py

### ISSUE THREAD

**Issue by dannyrohde** [jorisschellekens/borb#97]
**Describe the bug**
Between 2.0.21 and 2.0.24 the calculation of the layout_rect changed. This leads to an infinite loop in borb/pdf/canvas/layout/page_layout/multi_column_layout.py

The two pieces of code are line 193 and line 213:

```
        # attempt layout
        layout_rect = layout_element.layout(
            self._page, bounding_box=next_available_rect
        )
```

```
        # switch to next column
        if layout_rect.y < self._vertical_margin:
```

The calculation of layout_rect.y differs slightly between versions. In 2.0.21 the `if` branch in line 213 does not get triggered, while in 2.0.24 the layout_rect.y value is smaller than the vertical margin and the code steps into the `if` branch.

This leads to an infinite recursion where the code fails to fit the layout element (a table) on that page and keeps adding pages to the document. Eventually the code exceeds the maximum recursion depth and I get a stack trace. 

**To Reproduce**
Create a multi column (in my case 3x4) table that might be too big to fit onto the page. I've set the vertical margin to 36 and the layout_rect.y comes out as 33 in version 2.0.21, but 37 in version 2.0.24 without changing any of the code.

**Expected behaviour**
Two things:

1. The `if`branch should make sure if doesn't recurse infinitely. If the layout object doesn't fit on the page it won't fit onto the next page. In this case it should just raise with an informative error message.
2. The layout calculation between the two versions seems to differ. Not sure which is correct. If 2.0.24 is correct I might need to adjust my layout.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.3.1
 - borb version: 2.0.21 / 2.0.24
 - Python 3.9.12

**Additional context**
Stack trace (removed refs to other libraries that were not related):

Traceback (most recent call last):
[...]
2022-04-23T17:55:32.357513419Z   File "/app/./api_out/api/api_v1/endpoints/scanning.py", line 290, in download_labels
2022-04-23T17:55:32.357539226Z     label_page.add_label(label=product.label)
2022-04-23T17:55:32.357565895Z   File "/app/./api_out/business_logic/labels.py", line 360, in add_label
2022-04-23T17:55:32.357592229Z     self._finalize_page()
2022-04-23T17:55:32.357619284Z   File "/app/./api_out/business_logic/labels.py", line 342, in _finalize_page
2022-04-23T17:55:32.357645266Z     layout.add(table)
2022-04-23T17:55:32.357665577Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/page_layout/multi_column_layout.py", line 220, in add
2022-04-23T17:55:32.357686478Z     return self.add(layout_element)
2022-04-23T17:55:32.357705044Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/page_layout/multi_column_layout.py", line 220, in add
2022-04-23T17:55:32.357724323Z     return self.add(layout_element)
2022-04-23T17:55:32.357749931Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/page_layout/multi_column_layout.py", line 220, in add
2022-04-23T17:55:32.357775113Z     return self.add(layout_element)
2022-04-23T17:55:32.357795768Z   [Previous line repeated 946 more times]
2022-04-23T17:55:32.357823231Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/page_layout/multi_column_layout.py", line 193, in add
2022-04-23T17:55:32.357843687Z     layout_rect = layout_element.layout(
2022-04-23T17:55:32.357870992Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/layout_element.py", line 307, in layout
2022-04-23T17:55:32.357898700Z     return self.calculate_layout_box_and_do_layout(page, bounding_box)
2022-04-23T17:55:32.357926162Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/layout_element.py", line 320, in calculate_layout_box_and_do_layout
2022-04-23T17:55:32.357953566Z     layout_box = self._calculate_layout_box(page, bounding_box)
2022-04-23T17:55:32.357980429Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/layout_element.py", line 230, in _calculate_layout_box
2022-04-23T17:55:32.358012797Z     returned_layout_box = self._calculate_layout_box_without_padding(
2022-04-23T17:55:32.358040865Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/layout_element.py", line 258, in _calculate_layout_box_without_padding
2022-04-23T17:55:32.358068999Z     layout_rect = self._do_layout_without_padding(page, bounding_box)
2022-04-23T17:55:32.358097413Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/table/fixed_column_width_table.py", line 131, in _do_layout_without_padding
2022-04-23T17:55:32.358125461Z     t.layout(page, Rectangle(x, y, w, h))
2022-04-23T17:55:32.358153267Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/table/table.py", line 151, in layout
2022-04-23T17:55:32.358181007Z     returned_layout_box: Rectangle = self._layout_element.layout(
2022-04-23T17:55:32.358208778Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/layout_element.py", line 307, in layout
2022-04-23T17:55:32.358236311Z     return self.calculate_layout_box_and_do_layout(page, bounding_box)
2022-04-23T17:55:32.358256789Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/layout_element.py", line 360, in calculate_layout_box_and_do_layout
2022-04-23T17:55:32.358299880Z     final_layout_box = self._do_layout(page, bounding_box)
2022-04-23T17:55:32.358377250Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/layout_element.py", line 285, in _do_layout
2022-04-23T17:55:32.358409805Z     output_box = self._do_layout_without_padding(page, modified_bounding_box)
2022-04-23T17:55:32.358438660Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/image/image.py", line 128, in _do_layout_without_padding
2022-04-23T17:55:32.358466582Z     image_resource_name = self._get_image_resource_name(self._image, page)
2022-04-23T17:55:32.358488084Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/image/image.py", line 99, in _get_image_resource_name
2022-04-23T17:55:32.358514750Z     image_resource_name = [
2022-04-23T17:55:32.358535356Z   File "/venv/lib/python3.9/site-packages/borb/pdf/canvas/layout/image/image.py", line 100, in <listcomp>
2022-04-23T17:55:32.358561807Z     k for k, v in page["Resources"]["XObject"].items() if v == image
[...]
2022-04-23T17:55:32.358779822Z RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by jorisschellekens** [comment]
Hi @dannyrohde ,

There is not **correct layout mechanism**. I changed some minor details of the `LayoutElement` class. Mostly making sure that all its child-implementations have the same properties (`padding`, `margin`, etc). This may have changed some document layouts (certainly if these effects are compounded by putting things in a `Table`)

I will have a look at the recursion bug. That should really get fixed. Adding content that is too big to fit on an (empty) `Page` should just trigger an assert, rather than attempting to fit it on an empty (new) `Page`.

I'll have a look at the code this weekend.

Thank you for your patience,
Joris Schellekens

**Comment by dannyrohde** [comment]
> Hi @dannyrohde ,
> 
> There is not **correct layout mechanism**. I changed some minor details of the `LayoutElement` class. Mostly making sure that all its child-implementations have the same properties (`padding`, `margin`, etc). This may have changed some document layouts (certainly if these effects are compounded by putting things in a `Table`)
> 
> I will have a look at the recursion bug. That should really get fixed. Adding content that is too big to fit on an (empty) `Page` should just trigger an assert, rather than attempting to fit it on an empty (new) `Page`.
> 
> I'll have a look at the code this weekend.
> 
> Thank you for your patience, Joris Schellekens

Thanks Joris,

Do let me know if there is a new version to test. At the moment I've pinned 2.0.21 as I wasn't sure how to mitigate the recursion. Hopefully the exception in the new code will stop that. Then I can have a look what parameters work for the layout.

Have a good weekend,
Danny

**Comment by jorisschellekens** [comment]
Can you give me a concrete piece of code (as small as possible) that produces the bug?

**Comment by jorisschellekens** [comment]
Because I already have a test for this behaviour.
The test adds a `List` that is too large to fit on the `Page` and checks whether an `assert` is raised.
[This](https://github.com/jorisschellekens/borb/blob/e5e1377b36e71757a510a2094682a89d4d406a8a/tests/pdf/canvas/layout/list/test_write_long_unordered_list.py#L57) is the exact line.

**Comment by jorisschellekens** [comment]
Hi Danny,

I haven't heard back from you.
And like I indicated, I already have a test that checks this particular usecase. So it would be very interesting to see your code and figure out how your example is doing something different than my test.

I am going to close this ticket for lack of activity (a week without a reply from you after I asked for an example).
You are of course welcome to re-open the ticket (provided you supply a code sample that produces the bug).

Kind regards,
Joris Schellekens
